version: '3.5'
services:
    root-ca:
        build:
            context: .
        volumes:
        - ./scripts:/root-ca/scripts
        - ./configs:/root-ca/configs
        - "root-ca:/keypki"
        environment:
        - ROOT_CERT_PASS=test
    intermediate-ca:
        build:
            context: .
        volumes:
        - ./intermediate-ca:/

volumes:
  root-ca:
  intermediate-ca: